import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import Axios from "axios";
import { FirstQn } from "../components/data/firstQn";

const FirstQuestion = ({ questionNumber, setQuestionNumber, response }) => {
  //counter to keep track of the current question
  const [counter, setCounter] = useState(0);
  //verify to switch between verifications and confidence table
  const [verify, setVerify] = useState(true);

  //show video before verification
  const [showVideo, setShowVideo] = useState(true);

  //state to store the data
  const intialState = {
    name: "",
    age: 0,
    ethnicity: "",
    gender: "",
    option1: "",
    option1Confidence: 10,
    option2: "",
    option2Confidence: 10,
    option3: "",
    option3Confidence: 10,
    option4: "",
    option4Confidence: 10,
    option5: "",
    option5Confidence: 10,
    option6: "",
    option6Confidence: 10,
  };

  //set the data to the state
  const [data, setData] = useState(intialState);

  //set the data to the state from index page
  data.name = response.name;
  data.age = response.age;
  data.ethnicity = response.ethnicity;
  data.gender = response.gender;

  //handle change for the radio buttons
  const onHandleChange = (event) => {
    setData({ ...data, [event.target.name]: event.target.value });
  };

  //post the data to the database
  const submitData = async () => {
    await Axios.post("http://localhost:8080/api/insert/AfricanAmerican", {
      name: data.name,
      age: data.age,
      ethnicity: data.ethnicity,
      gender: data.gender,
      option1: data.option1,
      option1Confidence: data.option1Confidence,
      option2: data.option2,
      option2Confidence: data.option2Confidence,
      option3: data.option3,
      option3Confidence: data.option3Confidence,
      option4: data.option4,
      option4Confidence: data.option4Confidence,
      option5: data.option5,
      option5Confidence: data.option5Confidence,
      option6: data.option6,
      option6Confidence: data.option6Confidence,
    })
      .then(() => {
        alert("Data inserted successfully");
      })
      .catch((error) => {
        console.error(error);
        alert("An error occurred. Please try again.");
      });
  };

  //use setTimeout to change the counter every 3 seconds and switch between verifications and confidence table
  useEffect(() => {
    const timer = setTimeout(() => {
      const maxOption = FirstQn.length;

      if (showVideo == false && counter < maxOption && verify == true) {
        setVerify(false);
      }
    }, 3000);

    return () => clearTimeout(timer);
  });

  //on submit, change the counter and switch between verifications and confidence table
  const onSubmit = () => {
    setVerify(true);
    if (counter < FirstQn.length - 1) {
      setCounter(counter + 1);
    } else {
      setQuestionNumber(questionNumber + 1);
      submitData();
    }
  };

  return questionNumber == 1 ?showVideo ? (
    <>
      <Head>
        <title>Eyewitness Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
        <div className="bg-[#660000] m-1 w-fit">
          <div className="text-white text-center p-6">
            <p className="text-xl mt-2 mb-6">
              Please watch the video below and answer the following questions
            </p>
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/qHESfoVxC34"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            <button
              className="bg-blue-500 px-1 mt-6"
              onClick={() => setShowVideo(false)}
            >
              Show Question
            </button>
          </div>
        </div>
      </div>
    </>
  ) : (
    verify ? (
      <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
        <div className="bg-[#660000] m-1 w-fit">
          <Head>
            <title>First Question</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="text-white w-fit text-xl text-center mx-auto p-10">
            <p>{FirstQn[counter].name}</p>
            <img
              src={FirstQn[counter].src}
              alt="image"
              className="mx-auto h-[400px] w-[400px]"
            />
            <p className="my-4">Was this the person you saw in the video?</p>
            <label>
              <input
                type="radio"
                name={FirstQn[counter].name}
                value="yes"
                className="mr-2"
                onChange={onHandleChange}
              />
              Yes
            </label>
            <label className="ml-6">
              <input
                type="radio"
                name={FirstQn[counter].name}
                value="no"
                className="mr-2"
                onChange={onHandleChange}
              />
              No
            </label>
          </div>
        </div>
      </div>
    ) : (
      <div>
        <Head>
          <title>Eyewitness Video</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
          <div className="bg-[#660000] m-1 w-fit">
            <div className="text-white text-center p-6">
              <p className="text-xl mt-2 mb-6">
                How confident are you about this person?
              </p>
              <div className="space-x-[3rem] w-fit mx-auto">
                <span>1</span>
                <span>2</span>
                <span>3</span>
                <span>4</span>
                <span>5</span>
                <span>6</span>
                <span>7</span>
                <span>8</span>
                <span>9</span>
                <span>10</span>
              </div>
              <p className="space-x-[460px]">
                <span>Strongly</span>
                <span>Strongly</span>
              </p>
              <p className="space-x-[460px]">
                <span>Agree</span>
                <span> &nbsp; Disagree</span>
              </p>
              <div className="w-fit mx-auto">
                <input
                  type="range"
                  min="1"
                  max="10"
                  name={FirstQn[counter].confidence}
                  onChange={onHandleChange}
                  className="w-[540px]"
                />
              </div>
              <button
                onClick={onSubmit}
                className="bg-yellow-500 px-1 rounded-md mt-2"
              >
                Submit
              </button>
            </div>
          </div>
        </div>
      </div>
    )
  ) : (
    <></>
  );
};

export default FirstQuestion;
