import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import ConfidenceTable from "../components/ConfidenceTable";

const FourthQuestion = ({onQuestionResponse, questionNumber, setQuestionNumber}) => {
  const [currentQuestion, setCurrentQuestion] = useState(1);
  const [hideVideo, setHideVideo] = useState(false);
    useEffect(() => {
            const timer = setTimeout(function () {
            const maxQuestion = 7;
            const isDone = currentQuestion === maxQuestion;
            if (!isDone && hideVideo) {
                setCurrentQuestion(currentQuestion + 1);
            }
            }, 3000);
        return () => clearTimeout(timer);
      });
  return questionNumber == 4 ? (!hideVideo ? (
    <>
    <div className="my-10 mx-auto">
      <div className=" text-[#ffffff] text-xl  mx-10 md:mx-20 lg:mx-40 xl:mx-[20rem] 2xl:mx-[30rem]">
      <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
    <div className="mt-8">
          <iframe
            src="https://www.youtube.com/embed/5RBb1R8dFLo"
            className="w-full h-[30rem]"
          ></iframe>
        </div>
    </div>
    </div>
    <div className="w-fit mx-auto my-8">
        <button
          className="text-white bg-blue-500 px-6 py-1 rounded-md"
          onClick={() => setHideVideo(true)}
        >
          Ready
        </button>
      </div>
    </>
   ) : (
    <div className="w-fit my-10 mx-auto">
      <div className=" text-[#ffffff] text-xl  mx-10 md:mx-20 lg:mx-40 xl:mx-[20rem] 2xl:mx-[30rem]">
      <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <p className="text-xl font-bold mt-20">Question:4</p>
        <div className="bg-yellow-500 my-2 p-2">
          <div className="bg-[#660000] p-4 ">
            <Question1 show={currentQuestion == 1} onQuestionResponse={onQuestionResponse} />
            <Question2 show={currentQuestion == 2} onQuestionResponse={onQuestionResponse}/>
            <Question3 show={currentQuestion == 3} onQuestionResponse={onQuestionResponse}/>
            <Question4 show={currentQuestion == 4} onQuestionResponse={onQuestionResponse}/>
            <Question5 show={currentQuestion == 5} onQuestionResponse={onQuestionResponse}/>
            <Question6 show={currentQuestion == 6} onQuestionResponse={onQuestionResponse}/>
            <EndOfQuestion
              show={currentQuestion == 7}
              questionNumber={questionNumber}
              setQuestionNumber={setQuestionNumber}
            />
          </div>
        </div>
      </div>
    </div>
   )) : (<></>);
};

const Question1 = ({ show, onQuestionResponse }) => {
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture1.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable />
    </div>
  ) : (
    <></>
  );
};
const Question2 = ({ show }) => {
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture2.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable />
      </div>
    </div>
  ) : (
    <></>
  );
};

const Question3 = ({ show }) => {
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture3.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable />
    </div>
  ) : (
    <></>
  );
};
const Question4 = ({ show }) => {
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture4.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable />
      </div>
    </div>
  ) : (
    <></>
  );
};
const Question5 = ({ show }) => {
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture5.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable />
    </div>
  ) : (
    <></>
  );
};
const Question6 = ({ show }) => {
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture6.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable />
      </div>
    </div>
  ) : (
    <></>
  );
};

const EndOfQuestion = ({ show, questionNumber, setQuestionNumber }) => {
  return show ? (
    <div className="space-y-2">
      <p>That was a simulation of the upcoming task.</p>
      <p>Are there any questions?</p>
      <p>The first task will be the African American Female trial.</p>
      <p>Click to continue</p>
      <div className="w-fit mx-auto my-8">
        <button
          className="text-white bg-blue-500 px-6 py-1 rounded-md"
          onClick={() => setQuestionNumber(questionNumber+1)}
        >
          Start
        </button>
      </div>
    </div>
  ) : (
    <></>
  );
};

export default FourthQuestion;
