import Head from 'next/head'
import { useState } from 'react';
import Questions from './questions'
import {Data} from '../components/data/survey'
import Intro from './intro';

export default function Home() {

  const initialResponse = {
    "name": "",
    "cwid": "",
    "race": "",
    "q1": "no",
    "q2": "no",
    "q3": "no",
    "q4": "no",
    "q5": "no",
    "q6": "no",
    "q7": "no",
    "q8": "no",
  };

  const [response, onResponseChange] = useState(initialResponse);
  const [started, onStart] = useState(false);

  const handleNameChange = (event) => {
    onResponseChange({ ...response, "name": event.target.value });
  }

  const handleCWIDChange = (event) => {
    onResponseChange({ ...response, "cwid": event.target.value });
  }

  const handleRaceChange = (event) => {
    onResponseChange({ ...response, 'race': event.target.value });
  }

  const onQuestionReponse = (questionId, value) => {
    onResponseChange({ ...response, [questionId]: value });
  }

  const onComplete = () => {
    fetch("http://10.0.0.53:8080", {
      method: "POST",
      body: JSON.stringify(response),
      headers: { "Content-Type": "application/json" }
    })
      .then(response => response.text())
      .then(data => {
        console.log(data);
        globalThis.location = '/last';
      })
      .catch(err => console.error(err));
    console.log("completed");
  }

  return !started ? (
    <div>
      <div>
        <Head>
          <title>Eyewitness</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Intro/>
      <div className='text-3xl text-white bg-red relative top-10'>
        <div>
            <div className='w-fit mx-auto'>
              <p className='my-3' >Name:</p>
              <input name="name" type="text" className='w-[420px] text-black bg-gray-300' onChange={handleNameChange} />
              <p className='my-3'>CWID:</p>
              <input name="cwid" type="number" className='w-[420px] text-black bg-gray-300' onChange={handleCWIDChange} />
              <p className='my-3'>Race:</p>
              <input name="race" type="text" className='w-[420px] text-black bg-gray-300' onChange={handleRaceChange} />
            </div>
        </div>
      </div>
      <div className='w-fit mx-auto'>
        <button className="realtive mt-20 text-white bg-blue-500 px-6 py-1 rounded-md" onClick={() => onStart(true)}>
          Start
        </button>
      </div>
    </div>
  ) : (<Questions onQuestionResponse={onQuestionReponse} onComplete={onComplete} />);
}
