import Head from "next/head";
import { useState } from "react";
import Intro from "./intro";
import Sample from "./sample";
import Agreement from "./Agreement";
import FirstQuestion from "./firstQuestion";
import SecondQuestion from "./secondQuestion";
import ThirdQuestion from "./thirdQuestion";
import FourthQuestion from "./fourthQuestion";

export default function Home() {
  const initialResponse = {
    name: "",
    age: 0,
    ethnicity: "",
    gender:"",
  };

  const [response, onResponseChange] = useState(initialResponse);
  const [recordInfo, setRecordInfo] = useState(false);
  const [startedSurvey, onStartSurvey] = useState(false);
  const [showSample, setShowSample] = useState(false);
  const [questionNumber, setQuestionNumber] = useState(1);

  const onQuestionResponse = (questionId, value) => {
    onResponseChange({ ...response, [questionId]: value });
  };

  return !startedSurvey ? (
    showSample ? (
      <Sample onStartSurvey={onStartSurvey}/>
    ) : (
      <div>
        <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <Agreement recordInfo={recordInfo} setRecordInfo={setRecordInfo} />
        <Credential recordInfo={recordInfo} setShowSample={setShowSample} 
         onQuestionResponse={onQuestionResponse}/>
      </div>
    )
  ) : (
    <>
        <FirstQuestion response={response} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <SecondQuestion response={response} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <ThirdQuestion response={response} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <FourthQuestion response={response} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
    </>
  );
};

const Credential = ({recordInfo, setShowSample, onQuestionResponse}) => {
  return recordInfo ? (
  <div>
  <Intro onQuestionResponse={onQuestionResponse}/>
  <div className="w-fit mx-auto mb-8">
        <button
          className="bg-yellow-500 px-2 py-1 rounded-md text-md hover:bg-yellow-600"
          onClick={() => setShowSample(true)}
        >
          Continue
        </button>
        </div>
  </div>
  ) : (<></>)
}