import Head from "next/head";
import { useState } from "react";
import Intro from "./intro";
import Sample from "./sample";
import Agreement from "./Agreement";
import Questions from "./questions";
import FirstQuestion from "./firstQuestion";
import SecondQuestion from "./secondQuestion";
import ThirdQuestion from "./thirdQuestion";
import FourthQuestion from "./fourthQuestion";

export default function Home() {
  const initialResponse = {
    name: "",
    gender: "",
    age: "",
    ethnicity: "",
    q1: "no",
    q2: "no",
    q3: "no",
    q4: "no",
    q5: "no",
    q6: "no",
  };

  const [response, onResponseChange] = useState(initialResponse);
  const [recordInfo, setRecordInfo] = useState(false);
  const [startedSurvey, onStartSurvey] = useState(false);
  const [showSample, setShowSample] = useState(false);
  const [questionNumber, setQuestionNumber] = useState(1);

  const onQuestionResponse = (questionId, value) => {
    onResponseChange({ ...response, [questionId]: value });
  };

  const [surveyFinished, setSurveyFinished] = useState(false);
  const onComplete = () => {
    fetch("http://10.0.0.53:8080", {
      method: "POST",
      body: JSON.stringify(response),
      headers: { "Content-Type": "application/json"},
    })
      .then((response) => response.text())
      .then((data) => {
        console.log(data);
        globalThis.location = "/last";
      })
      .catch((err) => console.error(err));
    console.log("completed");
  };



  return !startedSurvey ? (
    showSample ? (
      <Sample startedSurvey={startedSurvey} onStartSurvey={onStartSurvey}
       onQuestionResponse={onQuestionResponse} onComplete={onComplete} />
    ) : (
      <div>
        <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <Agreement recordInfo={recordInfo} setRecordInfo={setRecordInfo} />
        <Credential recordInfo={recordInfo} setShowSample={setShowSample} 
         onQuestionResponse={onQuestionResponse}/>
      </div>
    )
  ) : (
    <>
        <FirstQuestion onQuestionResponse={onQuestionResponse} onComplete={onComplete} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <SecondQuestion onQuestionResponse={onQuestionResponse} onComplete={onComplete} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <ThirdQuestion onQuestionResponse={onQuestionResponse} onComplete={onComplete} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>
        <FourthQuestion onQuestionResponse={onQuestionResponse} onComplete={onComplete} questionNumber={questionNumber} setQuestionNumber={setQuestionNumber}/>

    </>
  );
};

const Credential = ({recordInfo, setShowSample, onQuestionResponse}) => {
  return recordInfo ? (
  <div>
  <Intro onQuestionResponse={onQuestionResponse}/>
  <div className="w-fit mx-auto mb-8">
        <button
          className="bg-yellow-500 px-2 py-1 rounded-md text-md hover:bg-yellow-600"
          onClick={() => setShowSample(true)}
        >
          Continue
        </button>
        </div>
  </div>
  ) : (<></>)
}