import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import { SampleQn } from "../components/data/SampleQn";

const SampleQuestion = ({ onStartSurvey }) => {
  //counter to keep track of the question number
  const [counter, setCounter] = useState(0);
  //verify to switch between verifications and confidence table
  const [verify, setVerify] = useState(true);
  //show video before the first question
  const [showVideo, setShowVideo] = useState(true);

  //use setTimeout to change the counter every 3 seconds and switch between verifications and confidence table
  useEffect(() => {
    const timer = setTimeout(() => {
      const maxOption = SampleQn.length;

      if (showVideo == false && counter < maxOption && verify == true) {
        setVerify(false);
      }
    }, 3000);

    return () => clearTimeout(timer);
  });

  const onSubmit = () => {
    setVerify(true);
    if (counter < SampleQn.length - 1) {
      setCounter(counter + 1);
    } else {
      onStartSurvey(true);
    }
  };

  return showVideo ? (
    <>
      <Head>
        <title>Eyewitness Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
        <div className="bg-[#660000] m-1 w-fit">
          <div className="text-white text-center p-6">
            <p className="text-xl mt-2 mb-6">
              Please watch the video below and answer the following questions
            </p>
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/qHESfoVxC34"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            <button
              className="bg-blue-500 px-1 mt-6"
              onClick={() => setShowVideo(false)}
            >
              Show Question
            </button>
          </div>
        </div>
      </div>
    </>
  ) : verify ? (
    <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
      <div className="bg-[#660000] m-1 w-fit">
        <Head>
          <title>Sample Question</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="text-white w-fit text-xl text-center mx-auto p-10">
          <p>{SampleQn[counter].name}</p>
          <img
            src={SampleQn[counter].src}
            alt="image"
            className="mx-auto h-[400px] w-[400px]"
          />
          <p className="my-4">Was this the person you saw in the video?</p>
          <label>
            <input
              type="radio"
              name={SampleQn[counter].name}
              value="yes"
              className="mr-2"
            />
            Yes
          </label>
          <label className="ml-6">
            <input
              type="radio"
              name={SampleQn[counter].name}
              value="no"
              className="mr-2"
            />
            No
          </label>
        </div>
      </div>
    </div>
  ) : (
    <div>
      <div className="my-16 bg-yellow-500 p-1 w-fit mx-auto">
        <div className="bg-[#660000] m-1 w-fit">
          <div className="text-white text-center p-6">
            <p className="text-xl mt-2 mb-6">
              How confident are you about this person?
            </p>
            <div className="space-x-[3rem] w-fit mx-auto">
              <span>1</span>
              <span>2</span>
              <span>3</span>
              <span>4</span>
              <span>5</span>
              <span>6</span>
              <span>7</span>
              <span>8</span>
              <span>9</span>
              <span>10</span>
            </div>
            <p className="space-x-[460px]">
              <span>Strongly</span>
              <span>Strongly</span>
            </p>
            <p className="space-x-[460px]">
              <span>Agree</span>
              <span> &nbsp; Disagree</span>
            </p>
            <div className="w-fit mx-auto">
              <input
                type="range"
                min="1"
                max="10"
                name={SampleQn[counter].confidence}
                className="w-[540px]"
              />
            </div>
            <button
              onClick={onSubmit}
              className="bg-yellow-500 px-1 rounded-md mt-2"
            >
              Submit
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SampleQuestion;
