import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import ConfidenceTable from "../components/ConfidenceTable";

const Sample = ({onQuestionResponse, onStartSurvey, onComplete}) => {
  const [currentSample, setSample] = useState(1);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const timer = setTimeout(function () {
      const maxSample = 7;
      const isDone = currentSample === maxSample;
      if (!isDone && ready) {
        setSample(currentSample + 1);
      }
      
    }, 3000);
    return () => clearTimeout(timer);
  });

  return !ready ? (
    <div className="w-fit my-10 ">
      <div className=" text-[#ffffff] text-xl  mx-10 md:mx-20 lg:mx-40 xl:mx-[20rem] 2xl:mx-[30rem]">
      <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <div className="mt-8">
          <iframe
            src="https://www.youtube.com/embed/8-9KCDxBpT4"
            className="w-full h-[30rem]"
          ></iframe>
        </div>
        <div className="mt-6">
          <p>
            Next, you will see a series of 6 faces. For each one you are to
            designate whether this is the face you saw in the precious video or
            not. You have 3 seconds to make a decision. Following that you will
            be ask to provide a confidence rating from 1 (least confident) to 10
            (most confident).
          </p>
          <p className="mt-6 text-center">when you are ready click here</p>
        </div>
        <div className="w-fit mx-auto mb-8">
        <button
          className="bg-yellow-500 px-2 py-1 my-4 rounded-md text-md hover:bg-yellow-600"
          onClick={() => setReady(true)}
        >
          Continue
        </button>
        </div>
      </div>
    </div>
  ) : (
    <div className="w-fit my-10 mx-auto">
      <div className=" text-[#ffffff] text-xl  mx-10 md:mx-20 lg:mx-40 xl:mx-[20rem] 2xl:mx-[30rem]">
      <div>
          <Head>
            <title>Eyewitness</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <p className="text-xl font-bold mt-20">Sample Question</p>
        <div className="bg-yellow-500 my-2 p-2">
          <div className="bg-[#660000] p-4 ">
            <Sample1 show={currentSample == 1} onQuestionResponse={onQuestionResponse} />
            <Sample2 show={currentSample == 2} onQuestionResponse={onQuestionResponse}/>
            <Sample3 show={currentSample == 3} onQuestionResponse={onQuestionResponse}/>
            <Sample4 show={currentSample == 4} onQuestionResponse={onQuestionResponse}/>
            <Sample5 show={currentSample == 5} onQuestionResponse={onQuestionResponse}/>
            <Sample6 show={currentSample == 6} onQuestionResponse={onQuestionResponse}/>
            <EndOfSample show={currentSample == 7} onStartSurvey={onStartSurvey} />
          </div>
        </div>
      </div>
    </div>
  );
};

const Sample1 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q1", event.target.value);
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture1.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable onConfidence={onConfidence} />
    </div>
  ) : (
    <></>
  );
};
const Sample2 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q2", event.target.value);
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture2.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable onConfidence={onConfidence} />
      </div>
    </div>
  ) : (
    <></>
  );
};

const Sample3 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q3", event.target.value);
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture3.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable onConfidence={onConfidence}/>
    </div>
  ) : (
    <></>
  );
};
const Sample4 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q4", event.target.value);
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture4.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable onConfidence={onConfidence}/>
      </div>
    </div>
  ) : (
    <></>
  );
};
const Sample5 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q5", event.target.value);
  return show ? (
    <div className="w-fit">
      <div>
        <img
          src="Picture5.svg"
          alt="sampleImage1"
          className="w-[400px] h-[400px] mx-auto"
        />
      </div>
      <ConfidenceTable onConfidence={onConfidence}/>
    </div>
  ) : (
    <></>
  );
};
const Sample6 = ({ show, onQuestionResponse }) => {
    const onConfidence = (event) => onQuestionResponse("q6", event.target.value);
  return show ? (
    <div>
      <div className="w-fit">
        <div>
          <img
            src="Picture6.svg"
            alt="sampleImage1"
            className="w-[400px] h-[400px] mx-auto"
          />
        </div>
        <ConfidenceTable onConfidence={onConfidence}/>
      </div>
    </div>
  ) : (
    <></>
  );
};

const EndOfSample = ({ show, onStartSurvey}) => {
  return show ? (
    <div className="space-y-2">
      <p>That was a simulation of the upcoming task.</p>
      <p>Are there any questions?</p>
      <p>The first task will be the African American Feamale trial.</p>
      <p>Click to continue</p>
      <div className="w-fit mx-auto my-8">
        <button className="text-white bg-blue-500 px-6 py-1 rounded-md" 
        onClick={() => onStartSurvey(true)}>
          Start
        </button>
      </div>
    </div>
  ) : (
    <></>
  );
};

export default Sample;
